# Generated by Django 4.1.5 on 2023-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose_of', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date_of_claim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
