# Generated by Django 4.1.5 on 2023-02-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_expenditure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('Electrical', 'Electrical'), ('Generator', 'Generator'), ('Electronics', 'Electronics'), ('Pump Technician', 'Pump Technician')], max_length=50)),
                ('possition_held', models.CharField(choices=[('Team leader', 'Team leader'), ('Technician Assis', 'Technician Assis'), ('Security', 'Security'), ('Department Manager', 'Department Manager'), ('Human Resource', 'Human Resource')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Nigeria', 'Nigeria'), ('Abijan', 'Abijan')], max_length=50)),
                ('id_of', models.CharField(choices=[('Passport', 'Passport'), ('Drivers lincense', 'Drivers lincense'), ('Voters ID', 'Voters ID'), ('Ghana Card', 'Ghana Card'), ('NHIS', 'NHIS'), ('SSNIT', 'SSNIT')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('midle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('other_name', models.CharField(blank=True, max_length=25, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('appointment_date', models.DateField()),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_title', to='management.job')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='management.nationality')),
                ('prove_of_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.nationality')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='management.job')),
            ],
        ),
    ]
