# Generated by Django 4.1.5 on 2023-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_job_nationality_employee_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_records',
            name='nationality',
        ),
        migrations.AddField(
            model_name='employee_records',
            name='nationalitys',
            field=models.CharField(choices=[('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Nigeria', 'Nigeria'), ('Abijan', 'Abijan')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='job_title',
            field=models.CharField(choices=[('Team leader', 'Team leader'), ('Technician Assis', 'Technician Assis'), ('Security', 'Security'), ('Department Manager', 'Department Manager'), ('Human Resource', 'Human Resource')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='prove_of_id',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Drivers lincense', 'Drivers lincense'), ('Voters ID', 'Voters ID'), ('Ghana Card', 'Ghana Card'), ('NHIS', 'NHIS'), ('SSNIT', 'SSNIT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='role',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Generator', 'Generator'), ('Electronics', 'Electronics'), ('Pump Technician', 'Pump Technician')], max_length=50),
        ),
    ]
