# Generated by Django 4.1.5 on 2023-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_employee_records_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_records',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Team leader', 'Team leader'), ('Technician Assis', 'Technician Assis'), ('Security', 'Security'), ('Department Manager', 'Department Manager'), ('Human Resource', 'Human Resource')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='nationalitys',
            field=models.CharField(blank=True, choices=[('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Nigeria', 'Nigeria'), ('Abijan', 'Abijan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='prove_of_id',
            field=models.CharField(blank=True, choices=[('Passport', 'Passport'), ('Drivers lincense', 'Drivers lincense'), ('Voters ID', 'Voters ID'), ('Ghana Card', 'Ghana Card'), ('NHIS', 'NHIS'), ('SSNIT', 'SSNIT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='role',
            field=models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Generator', 'Generator'), ('Electronics', 'Electronics'), ('Pump Technician', 'Pump Technician')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='possition_held',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='roles',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id_of',
            field=models.CharField(max_length=50),
        ),
    ]
