# Generated by Django 4.1.5 on 2023-02-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_employee_records_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possition_held', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='employee_records',
            old_name='nationalitys',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='nationality',
            old_name='country',
            new_name='countries',
        ),
        migrations.RemoveField(
            model_name='job',
            name='possition_held',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='id_of',
        ),
    ]
