# Generated by Django 4.1.5 on 2023-02-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_identitycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_records',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Team leader', 'Team leader'), ('Technician Assis', 'Technician Assis'), ('Security', 'Security'), ('Department Manager', 'Department Manager'), ('Human Resource', 'Human Resource')], default='Team leader', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Ghana', 'Ghana'), ('Togo', 'Togo'), ('Nigeria', 'Nigeria'), ('Abijan', 'Abijan')], default='Ghana', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='prove_of_id',
            field=models.CharField(blank=True, choices=[('Passport', 'Passport'), ('Drivers lincense', 'Drivers lincense'), ('Voters ID', 'Voters ID'), ('Ghana Card', 'Ghana Card'), ('NHIS', 'NHIS'), ('SSNIT', 'SSNIT')], default='Ghana Card', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_records',
            name='role',
            field=models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Generator', 'Generator'), ('Electronics', 'Electronics'), ('Pump Technician', 'Pump Technician')], default='Pump Technician', max_length=50, null=True),
        ),
    ]
